import { GENERATED_CLINICAL_KNOWLEDGE, GENERATED_RED_FLAG_RULES } from './clinical-index.generated';

export type ClinicalConfidence = 'high' | 'medium' | 'low';

export type ClinicalKnowledgeEntry = {
  id: string;
  system: string;
  medical: string;
  synonyms: string[];
  activeIngredients: string[];
  confidence: ClinicalConfidence;
};

export type RedFlagRule = {
  label: string;
  terms: string[];
};

const CURATED_CLINICAL_KNOWLEDGE: ClinicalKnowledgeEntry[] = [
  {
    id: 'cefalea',
    system: 'Neurologia',
    medical: 'cefalea',
    synonyms: ['dolor cabeza', 'dolor de cabeza', 'cefalea'],
    activeIngredients: ['paracetamol', 'ibuprofeno', 'acido acetilsalicilico'],
    confidence: 'high',
  },
  {
    id: 'migrana',
    system: 'Neurologia',
    medical: 'migrana',
    synonyms: ['migrana', 'jaqueca'],
    activeIngredients: ['sumatriptan', 'almotriptan', 'zolmitriptan'],
    confidence: 'medium',
  },
  {
    id: 'vertigo',
    system: 'ORL / vestibular',
    medical: 'vertigo',
    synonyms: ['mareo', 'vertigo', 'vértigo'],
    activeIngredients: ['betahistina', 'dimenhidrinato'],
    confidence: 'medium',
  },
  {
    id: 'fiebre',
    system: 'Sistemico',
    medical: 'fiebre',
    synonyms: ['fiebre', 'febricula', 'calentura'],
    activeIngredients: ['paracetamol', 'ibuprofeno'],
    confidence: 'high',
  },
  {
    id: 'resfriado',
    system: 'Respiratorio',
    medical: 'resfriado comun',
    synonyms: ['resfriado', 'catarro', 'constipado', 'gripe', 'mocos'],
    activeIngredients: ['paracetamol', 'pseudoefedrina', 'dextrometorfano', 'acetilcisteina'],
    confidence: 'medium',
  },
  {
    id: 'congestion-nasal',
    system: 'Respiratorio / ORL',
    medical: 'congestion nasal',
    synonyms: ['congestion nasal', 'nariz tapada', 'mocos nariz'],
    activeIngredients: ['xilometazolina', 'oximetazolina', 'pseudoefedrina'],
    confidence: 'high',
  },
  {
    id: 'tos-seca',
    system: 'Respiratorio',
    medical: 'tos seca',
    synonyms: ['tos seca', 'tos irritativa'],
    activeIngredients: ['dextrometorfano', 'levodropropizina'],
    confidence: 'high',
  },
  {
    id: 'tos-productiva',
    system: 'Respiratorio',
    medical: 'tos productiva',
    synonyms: ['tos con flemas', 'tos productiva', 'flemas', 'expectoracion'],
    activeIngredients: ['acetilcisteina', 'ambroxol'],
    confidence: 'high',
  },
  {
    id: 'rinitis-alergica',
    system: 'Alergia / ORL',
    medical: 'rinitis alergica',
    synonyms: ['alergia', 'rinitis alergica', 'mocos alergia', 'estornudos alergia'],
    activeIngredients: ['cetirizina', 'loratadina', 'desloratadina'],
    confidence: 'medium',
  },
  {
    id: 'dolor-garganta',
    system: 'ORL',
    medical: 'dolor de garganta',
    synonyms: ['dolor garganta', 'dolor de garganta', 'irritacion garganta', 'faringitis'],
    activeIngredients: ['flurbiprofeno', 'bencidamina'],
    confidence: 'medium',
  },
  {
    id: 'acidez',
    system: 'Digestivo',
    medical: 'acidez',
    synonyms: ['acidez', 'ardor estomago', 'ardor de estomago', 'reflujo', 'quemazon'],
    activeIngredients: ['magaldrato', 'algeldrato', 'famotidina', 'omeprazol'],
    confidence: 'high',
  },
  {
    id: 'dolor-abdominal',
    system: 'Digestivo',
    medical: 'dolor abdominal',
    synonyms: ['dolor estomago', 'dolor de estomago', 'dolor barriga', 'dolor abdominal'],
    activeIngredients: ['butilescopolamina', 'simeticona', 'paracetamol'],
    confidence: 'low',
  },
  {
    id: 'gastroenteritis',
    system: 'Digestivo',
    medical: 'gastroenteritis',
    synonyms: ['gastroenteritis', 'diarrea con vomitos', 'diarrea y vomitos'],
    activeIngredients: ['racecadotrilo', 'loperamida', 'dimenhidrinato'],
    confidence: 'medium',
  },
  {
    id: 'diarrea',
    system: 'Digestivo',
    medical: 'diarrea',
    synonyms: ['diarrea', 'diarreico'],
    activeIngredients: ['loperamida', 'racecadotrilo'],
    confidence: 'high',
  },
  {
    id: 'estrenimiento',
    system: 'Digestivo',
    medical: 'estrenimiento',
    synonyms: ['estrenimiento', 'estreñimiento'],
    activeIngredients: ['macrogol', 'lactulosa', 'bisacodilo'],
    confidence: 'high',
  },
  {
    id: 'nauseas-vomitos',
    system: 'Digestivo / vestibular',
    medical: 'nauseas y vomitos',
    synonyms: ['nauseas', 'nausea', 'vomitos', 'vomito'],
    activeIngredients: ['dimenhidrinato', 'metoclopramida', 'domperidona'],
    confidence: 'medium',
  },
  {
    id: 'dolor-articular',
    system: 'Musculoesqueletico',
    medical: 'dolor articular',
    synonyms: [
      'dolor rodilla',
      'dolor de rodilla',
      'dolor rodillas',
      'dolor de rodillas',
      'dolor articulacion',
    ],
    activeIngredients: ['ibuprofeno', 'naproxeno', 'diclofenaco', 'paracetamol'],
    confidence: 'medium',
  },
  {
    id: 'dolor-muscular',
    system: 'Musculoesqueletico',
    medical: 'dolor muscular',
    synonyms: ['dolor muscular', 'mialgia', 'contractura'],
    activeIngredients: ['ibuprofeno', 'naproxeno', 'diclofenaco', 'paracetamol'],
    confidence: 'medium',
  },
  {
    id: 'lumbalgia',
    system: 'Musculoesqueletico',
    medical: 'lumbalgia',
    synonyms: ['dolor espalda', 'dolor lumbar', 'lumbalgia'],
    activeIngredients: ['ibuprofeno', 'diclofenaco', 'naproxeno', 'paracetamol'],
    confidence: 'medium',
  },
  {
    id: 'odontalgia',
    system: 'Odontologia',
    medical: 'odontalgia',
    synonyms: ['dolor muelas', 'dolor de muelas', 'dolor dental', 'dolor diente'],
    activeIngredients: ['ibuprofeno', 'paracetamol', 'metamizol'],
    confidence: 'medium',
  },
  {
    id: 'dismenorrea',
    system: 'Ginecologia',
    medical: 'dismenorrea',
    synonyms: ['dolor menstrual', 'dolor regla', 'dismenorrea'],
    activeIngredients: ['ibuprofeno', 'naproxeno', 'metamizol'],
    confidence: 'medium',
  },
  {
    id: 'prurito',
    system: 'Dermatologia / alergia',
    medical: 'prurito o alergia',
    synonyms: ['picor', 'picazon', 'picazon piel', 'picor piel', 'prurito', 'urticaria', 'ronchas'],
    activeIngredients: ['cetirizina', 'loratadina', 'desloratadina'],
    confidence: 'medium',
  },
  {
    id: 'dermatitis',
    system: 'Dermatologia',
    medical: 'dermatitis',
    synonyms: ['dermatitis', 'eczema', 'eccema', 'sarpullido', 'eritema', 'rojez piel'],
    activeIngredients: ['hidrocortisona', 'dexclorfeniramina', 'cetirizina'],
    confidence: 'medium',
  },
  {
    id: 'micosis',
    system: 'Dermatologia',
    medical: 'micosis cutanea',
    synonyms: ['hongos', 'micosis', 'candidiasis', 'pie atleta'],
    activeIngredients: ['clotrimazol', 'ketoconazol'],
    confidence: 'medium',
  },
  {
    id: 'disuria-cistitis',
    system: 'Urologia',
    medical: 'disuria / cistitis',
    synonyms: ['escozor al orinar', 'dolor al orinar', 'cistitis', 'disuria'],
    activeIngredients: ['fosfomicina'],
    confidence: 'low',
  },
  {
    id: 'herida',
    system: 'Curas',
    medical: 'herida cutanea',
    synonyms: ['herida', 'corte', 'quemadura leve'],
    activeIngredients: ['clorhexidina'],
    confidence: 'medium',
  },
  {
    id: 'malestar-general',
    system: 'Sistemico',
    medical: 'malestar general',
    synonyms: ['malestar general', 'quebranto', 'cuerpo cortado', 'astenia', 'decaimiento'],
    activeIngredients: ['paracetamol', 'ibuprofeno'],
    confidence: 'low',
  },
  {
    id: 'dolor-toracico',
    system: 'Cardiovascular / urgencias',
    medical: 'dolor toracico',
    synonyms: ['dolor toracico', 'dolor pecho', 'opresion toracica', 'opresion pecho'],
    activeIngredients: ['acido acetilsalicilico', 'nitroglicerina'],
    confidence: 'low',
  },
  {
    id: 'taquicardia-palpitaciones',
    system: 'Cardiovascular',
    medical: 'taquicardia / palpitaciones',
    synonyms: [
      'taquicardia',
      'palpitaciones',
      'corazon acelerado',
      'latidos rapidos',
      'ritmo cardiaco rapido',
    ],
    activeIngredients: ['bisoprolol', 'propranolol', 'atenolol'],
    confidence: 'low',
  },
  {
    id: 'hipertension',
    system: 'Cardiovascular',
    medical: 'hipertension arterial',
    synonyms: ['hipertension', 'tension alta', 'presion alta', 'hta'],
    activeIngredients: ['enalapril', 'losartan', 'amlodipino', 'hidroclorotiazida'],
    confidence: 'low',
  },
  {
    id: 'asma-broncoespasmo',
    system: 'Respiratorio',
    medical: 'asma / broncoespasmo',
    synonyms: ['asma', 'broncoespasmo', 'pitos pecho', 'sibilancias'],
    activeIngredients: ['salbutamol', 'budesonida', 'formoterol', 'terbutalina'],
    confidence: 'low',
  },
  {
    id: 'disnea',
    system: 'Respiratorio / urgencias',
    medical: 'disnea',
    synonyms: ['disnea', 'falta aire', 'dificultad respirar', 'ahogo'],
    activeIngredients: ['salbutamol', 'ipratropio', 'budesonida'],
    confidence: 'low',
  },
  {
    id: 'sinusitis',
    system: 'ORL',
    medical: 'sinusitis',
    synonyms: ['sinusitis', 'dolor senos paranasales', 'presion facial', 'dolor cara mocos'],
    activeIngredients: ['paracetamol', 'ibuprofeno', 'mometasona', 'amoxicilina'],
    confidence: 'low',
  },
  {
    id: 'otalgia',
    system: 'ORL',
    medical: 'otalgia',
    synonyms: ['otalgia', 'dolor oido', 'dolor de oido', 'otitis'],
    activeIngredients: ['paracetamol', 'ibuprofeno', 'ciprofloxacino'],
    confidence: 'low',
  },
  {
    id: 'conjuntivitis',
    system: 'Oftalmologia',
    medical: 'conjuntivitis',
    synonyms: ['conjuntivitis', 'ojo rojo', 'ojos rojos', 'picor ojos', 'secrecion ocular'],
    activeIngredients: ['azelastina', 'olopatadina', 'tobramicina'],
    confidence: 'low',
  },
  {
    id: 'sequedad-ocular',
    system: 'Oftalmologia',
    medical: 'sequedad ocular',
    synonyms: ['ojo seco', 'ojos secos', 'sequedad ocular', 'lagrima artificial'],
    activeIngredients: ['hipromelosa', 'carmelosa', 'acido hialuronico'],
    confidence: 'medium',
  },
  {
    id: 'flatulencia',
    system: 'Digestivo',
    medical: 'meteorismo / flatulencia',
    synonyms: ['gases', 'flatulencia', 'meteorismo', 'hinchazon abdominal'],
    activeIngredients: ['simeticona', 'dimeticona'],
    confidence: 'high',
  },
  {
    id: 'gastritis-dispepsia',
    system: 'Digestivo',
    medical: 'dispepsia / gastritis',
    synonyms: ['gastritis', 'dispepsia', 'pesadez estomago', 'mala digestion', 'indigestion'],
    activeIngredients: ['omeprazol', 'famotidina', 'magaldrato', 'algeldrato'],
    confidence: 'medium',
  },
  {
    id: 'hemorroides',
    system: 'Digestivo',
    medical: 'hemorroides',
    synonyms: ['hemorroides', 'almorranas', 'picor anal', 'dolor anal'],
    activeIngredients: ['hidrocortisona', 'lidocaina', 'ruscogenina'],
    confidence: 'medium',
  },
  {
    id: 'acne',
    system: 'Dermatologia',
    medical: 'acne',
    synonyms: ['acne', 'granos', 'espinillas', 'comedones'],
    activeIngredients: ['peroxido de benzoilo', 'adapaleno', 'clindamicina'],
    confidence: 'medium',
  },
  {
    id: 'psoriasis',
    system: 'Dermatologia',
    medical: 'psoriasis',
    synonyms: ['psoriasis', 'placas piel', 'escamas piel'],
    activeIngredients: ['calcipotriol', 'betametasona', 'clobetasol'],
    confidence: 'low',
  },
  {
    id: 'herpes-labial',
    system: 'Dermatologia / infecciosas',
    medical: 'herpes labial',
    synonyms: ['herpes labial', 'calentura labio', 'pupa labio', 'vesiculas labio'],
    activeIngredients: ['aciclovir', 'penciclovir'],
    confidence: 'medium',
  },
  {
    id: 'pediculosis',
    system: 'Dermatologia / parasitosis',
    medical: 'pediculosis',
    synonyms: ['piojos', 'pediculosis', 'liendres'],
    activeIngredients: ['permetrina', 'dimeticona'],
    confidence: 'high',
  },
  {
    id: 'escabiosis',
    system: 'Dermatologia / parasitosis',
    medical: 'escabiosis',
    synonyms: ['sarna', 'escabiosis'],
    activeIngredients: ['permetrina', 'ivermectina'],
    confidence: 'medium',
  },
  {
    id: 'vaginitis-candidiasis',
    system: 'Ginecologia / infecciosas',
    medical: 'vaginitis / candidiasis',
    synonyms: ['vaginitis', 'candidiasis vaginal', 'picor vaginal', 'flujo vaginal'],
    activeIngredients: ['clotrimazol', 'fluconazol', 'metronidazol'],
    confidence: 'low',
  },
  {
    id: 'gota',
    system: 'Reumatologia',
    medical: 'gota',
    synonyms: ['gota', 'ataque gota', 'podagra', 'acido urico alto'],
    activeIngredients: ['colchicina', 'alopurinol', 'naproxeno', 'ibuprofeno'],
    confidence: 'low',
  },
  {
    id: 'tendinitis',
    system: 'Musculoesqueletico',
    medical: 'tendinitis',
    synonyms: ['tendinitis', 'tendinopatia', 'dolor tendon'],
    activeIngredients: ['ibuprofeno', 'naproxeno', 'diclofenaco'],
    confidence: 'medium',
  },
  {
    id: 'insomnio',
    system: 'Neurologia / salud mental',
    medical: 'insomnio',
    synonyms: ['insomnio', 'no puedo dormir', 'dificultad dormir'],
    activeIngredients: ['doxilamina', 'melatonina', 'zolpidem'],
    confidence: 'low',
  },
  {
    id: 'ansiedad',
    system: 'Salud mental',
    medical: 'ansiedad',
    synonyms: ['ansiedad', 'crisis ansiedad', 'nerviosismo', 'ataque panico'],
    activeIngredients: ['diazepam', 'lorazepam', 'alprazolam'],
    confidence: 'low',
  },
  {
    id: 'hipoglucemia',
    system: 'Endocrinologia',
    medical: 'hipoglucemia',
    synonyms: ['hipoglucemia', 'azucar bajo', 'glucosa baja'],
    activeIngredients: ['glucosa', 'glucagon'],
    confidence: 'low',
  },
  {
    id: 'anemia',
    system: 'Hematologia',
    medical: 'anemia',
    synonyms: ['anemia', 'ferropenia', 'hierro bajo'],
    activeIngredients: ['hierro', 'sulfato ferroso', 'acido folico', 'cianocobalamina'],
    confidence: 'low',
  },
];

export const CLINICAL_KNOWLEDGE: ClinicalKnowledgeEntry[] = [
  ...CURATED_CLINICAL_KNOWLEDGE,
  ...GENERATED_CLINICAL_KNOWLEDGE,
];

const CURATED_RED_FLAG_RULES: RedFlagRule[] = [
  { label: 'dolor toracico', terms: ['dolor pecho', 'dolor toracico', 'opresion pecho'] },
  {
    label: 'taquicardia o palpitaciones',
    terms: ['taquicardia', 'palpitaciones', 'corazon acelerado'],
  },
  { label: 'disnea', terms: ['dificultad respirar', 'falta aire', 'disnea', 'ahogo'] },
  { label: 'cefalea con rigidez cervical', terms: ['rigidez nuca', 'cuello rigido'] },
  { label: 'sangrado digestivo', terms: ['sangre heces', 'vomito sangre', 'heces negras'] },
  { label: 'embarazo', terms: ['embarazada', 'embarazo'] },
  {
    label: 'dolor abdominal intenso',
    terms: ['dolor abdominal intenso', 'dolor estomago intenso'],
  },
];

export const RED_FLAG_RULES: RedFlagRule[] = [
  ...CURATED_RED_FLAG_RULES,
  ...GENERATED_RED_FLAG_RULES,
];
