// Auto-generated by tools/build-clinical-index.mjs. Do not edit by hand.
// Source: src/app/features/search/data/clinical-source.json

import type { ClinicalKnowledgeEntry, RedFlagRule } from './clinical-knowledge';

export const CLINICAL_INDEX_VERSION = 1;

export const GENERATED_CLINICAL_KNOWLEDGE: ClinicalKnowledgeEntry[] = [
  {
    "id": "anafilaxia",
    "system": "Alergia / urgencias",
    "medical": "anafilaxia",
    "synonyms": [
      "anafilaxia",
      "shock anafilactico",
      "reaccion alergica grave"
    ],
    "activeIngredients": [
      "adrenalina",
      "dexclorfeniramina",
      "metilprednisolona"
    ],
    "confidence": "low"
  },
  {
    "id": "anemia-megaloblastica",
    "system": "Hematologia",
    "medical": "deficit de vitamina B12 / folato",
    "synonyms": [
      "vitamina b12 baja",
      "deficit b12",
      "folato bajo",
      "acido folico bajo"
    ],
    "activeIngredients": [
      "cianocobalamina",
      "hidroxocobalamina",
      "acido folico"
    ],
    "confidence": "low"
  },
  {
    "id": "anticoncepcion",
    "system": "Ginecologia",
    "medical": "anticoncepcion",
    "synonyms": [
      "anticoncepcion",
      "anticonceptivo",
      "pastilla anticonceptiva",
      "contracepcion"
    ],
    "activeIngredients": [
      "levonorgestrel",
      "etinilestradiol",
      "drospirenona",
      "desogestrel"
    ],
    "confidence": "medium"
  },
  {
    "id": "artritis",
    "system": "Reumatologia",
    "medical": "artritis",
    "synonyms": [
      "artritis",
      "articulacion inflamada",
      "dolor inflamatorio"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "metotrexato",
      "prednisona"
    ],
    "confidence": "low"
  },
  {
    "id": "artrosis",
    "system": "Reumatologia",
    "medical": "artrosis",
    "synonyms": [
      "artrosis",
      "osteoartritis",
      "desgaste articulacion"
    ],
    "activeIngredients": [
      "paracetamol",
      "ibuprofeno",
      "naproxeno",
      "diclofenaco"
    ],
    "confidence": "medium"
  },
  {
    "id": "blefaritis",
    "system": "Oftalmologia",
    "medical": "blefaritis",
    "synonyms": [
      "blefaritis",
      "parpado inflamado",
      "costras parpados"
    ],
    "activeIngredients": [
      "azitromicina",
      "tobramicina",
      "dexametasona"
    ],
    "confidence": "low"
  },
  {
    "id": "bronquitis",
    "system": "Respiratorio",
    "medical": "bronquitis",
    "synonyms": [
      "bronquitis",
      "tos persistente",
      "tos bronquial"
    ],
    "activeIngredients": [
      "salbutamol",
      "budesonida",
      "dextrometorfano",
      "acetilcisteina"
    ],
    "confidence": "low"
  },
  {
    "id": "celulitis-infecciosa",
    "system": "Dermatologia / infecciosas",
    "medical": "celulitis infecciosa",
    "synonyms": [
      "celulitis infecciosa",
      "piel roja caliente",
      "infeccion piel"
    ],
    "activeIngredients": [
      "amoxicilina",
      "cloxacilina",
      "cefadroxilo"
    ],
    "confidence": "low"
  },
  {
    "id": "cervicalgia-cervical",
    "system": "Musculoesqueletico",
    "medical": "cervicalgia",
    "synonyms": [
      "dolor cervical",
      "dolor de cervical",
      "dolor en cervical",
      "molestia cervical",
      "molestia en cervical"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "cervicalgia-cervicales",
    "system": "Musculoesqueletico",
    "medical": "cervicalgia",
    "synonyms": [
      "dolor cervicales",
      "dolor de cervicales",
      "dolor en cervicales",
      "molestia cervicales",
      "molestia en cervicales"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "cervicalgia-cuello",
    "system": "Musculoesqueletico",
    "medical": "cervicalgia",
    "synonyms": [
      "dolor cuello",
      "dolor de cuello",
      "dolor en cuello",
      "molestia cuello",
      "molestia en cuello"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "cervicalgia-nuca",
    "system": "Musculoesqueletico",
    "medical": "cervicalgia",
    "synonyms": [
      "dolor nuca",
      "dolor de nuca",
      "dolor en nuca",
      "molestia nuca",
      "molestia en nuca"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "colico-biliar",
    "system": "Digestivo",
    "medical": "colico biliar",
    "synonyms": [
      "colico biliar",
      "dolor vesicula",
      "piedras vesicula"
    ],
    "activeIngredients": [
      "metamizol",
      "paracetamol",
      "butilescopolamina"
    ],
    "confidence": "low"
  },
  {
    "id": "colico-renal",
    "system": "Urologia",
    "medical": "colico renal",
    "synonyms": [
      "colico renal",
      "piedra riñon",
      "litiasis renal",
      "dolor riñon"
    ],
    "activeIngredients": [
      "dexketoprofeno",
      "diclofenaco",
      "metamizol",
      "tamsulosina"
    ],
    "confidence": "low"
  },
  {
    "id": "depresion",
    "system": "Salud mental",
    "medical": "depresion",
    "synonyms": [
      "depresion",
      "estado depresivo",
      "animo bajo",
      "tristeza persistente"
    ],
    "activeIngredients": [
      "sertralina",
      "escitalopram",
      "fluoxetina",
      "venlafaxina"
    ],
    "confidence": "low"
  },
  {
    "id": "diabetes",
    "system": "Endocrinologia",
    "medical": "diabetes mellitus",
    "synonyms": [
      "diabetes",
      "azucar alto",
      "glucosa alta",
      "hiperglucemia"
    ],
    "activeIngredients": [
      "metformina",
      "insulina",
      "semaglutida",
      "empagliflozina"
    ],
    "confidence": "low"
  },
  {
    "id": "disfuncion-erectil",
    "system": "Urologia / andrologia",
    "medical": "disfuncion erectil",
    "synonyms": [
      "disfuncion erectil",
      "disfunción eréctil",
      "impotencia",
      "problemas ereccion",
      "problemas de ereccion",
      "falta ereccion"
    ],
    "activeIngredients": [
      "sildenafilo",
      "tadalafilo",
      "vardenafilo",
      "avanafilo"
    ],
    "confidence": "medium"
  },
  {
    "id": "dislipemia",
    "system": "Cardiovascular",
    "medical": "dislipemia",
    "synonyms": [
      "dislipemia",
      "colesterol alto",
      "trigliceridos altos",
      "hipercolesterolemia"
    ],
    "activeIngredients": [
      "atorvastatina",
      "simvastatina",
      "rosuvastatina",
      "ezetimiba"
    ],
    "confidence": "low"
  },
  {
    "id": "dolor-cadera-cadera",
    "system": "Musculoesqueletico",
    "medical": "dolor de cadera",
    "synonyms": [
      "dolor cadera",
      "dolor de cadera",
      "dolor en cadera",
      "molestia cadera",
      "molestia en cadera"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-cadera-caderas",
    "system": "Musculoesqueletico",
    "medical": "dolor de cadera",
    "synonyms": [
      "dolor caderas",
      "dolor de caderas",
      "dolor en caderas",
      "molestia caderas",
      "molestia en caderas"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-hombro-hombro",
    "system": "Musculoesqueletico",
    "medical": "dolor de hombro",
    "synonyms": [
      "dolor hombro",
      "dolor de hombro",
      "dolor en hombro",
      "molestia hombro",
      "molestia en hombro"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-hombro-hombros",
    "system": "Musculoesqueletico",
    "medical": "dolor de hombro",
    "synonyms": [
      "dolor hombros",
      "dolor de hombros",
      "dolor en hombros",
      "molestia hombros",
      "molestia en hombros"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-mano-muneca-dedo",
    "system": "Musculoesqueletico",
    "medical": "dolor de mano / muñeca",
    "synonyms": [
      "dolor dedo",
      "dolor de dedo",
      "dolor en dedo",
      "molestia dedo",
      "molestia en dedo"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-mano-muneca-dedos",
    "system": "Musculoesqueletico",
    "medical": "dolor de mano / muñeca",
    "synonyms": [
      "dolor dedos",
      "dolor de dedos",
      "dolor en dedos",
      "molestia dedos",
      "molestia en dedos"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-mano-muneca-mano",
    "system": "Musculoesqueletico",
    "medical": "dolor de mano / muñeca",
    "synonyms": [
      "dolor mano",
      "dolor de mano",
      "dolor en mano",
      "molestia mano",
      "molestia en mano"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-mano-muneca-manos",
    "system": "Musculoesqueletico",
    "medical": "dolor de mano / muñeca",
    "synonyms": [
      "dolor manos",
      "dolor de manos",
      "dolor en manos",
      "molestia manos",
      "molestia en manos"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-mano-muneca-muneca",
    "system": "Musculoesqueletico",
    "medical": "dolor de mano / muñeca",
    "synonyms": [
      "dolor muñeca",
      "dolor de muñeca",
      "dolor en muñeca",
      "molestia muñeca",
      "molestia en muñeca"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-mano-muneca-munecas",
    "system": "Musculoesqueletico",
    "medical": "dolor de mano / muñeca",
    "synonyms": [
      "dolor muñecas",
      "dolor de muñecas",
      "dolor en muñecas",
      "molestia muñecas",
      "molestia en muñecas"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-pelvico-bajo-vientre",
    "system": "Ginecologia / urologia",
    "medical": "dolor pelvico",
    "synonyms": [
      "dolor bajo vientre",
      "dolor de bajo vientre",
      "dolor en bajo vientre",
      "molestia bajo vientre",
      "molestia en bajo vientre"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "metamizol",
      "paracetamol"
    ],
    "confidence": "low"
  },
  {
    "id": "dolor-pelvico-pelvico",
    "system": "Ginecologia / urologia",
    "medical": "dolor pelvico",
    "synonyms": [
      "dolor pelvico",
      "dolor de pelvico",
      "dolor en pelvico",
      "molestia pelvico",
      "molestia en pelvico"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "metamizol",
      "paracetamol"
    ],
    "confidence": "low"
  },
  {
    "id": "dolor-pelvico-pelvis",
    "system": "Ginecologia / urologia",
    "medical": "dolor pelvico",
    "synonyms": [
      "dolor pelvis",
      "dolor de pelvis",
      "dolor en pelvis",
      "molestia pelvis",
      "molestia en pelvis"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "metamizol",
      "paracetamol"
    ],
    "confidence": "low"
  },
  {
    "id": "dolor-tobillo-pie-pie",
    "system": "Musculoesqueletico",
    "medical": "dolor de tobillo / pie",
    "synonyms": [
      "dolor pie",
      "dolor de pie",
      "dolor en pie",
      "molestia pie",
      "molestia en pie"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-tobillo-pie-pies",
    "system": "Musculoesqueletico",
    "medical": "dolor de tobillo / pie",
    "synonyms": [
      "dolor pies",
      "dolor de pies",
      "dolor en pies",
      "molestia pies",
      "molestia en pies"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-tobillo-pie-talon",
    "system": "Musculoesqueletico",
    "medical": "dolor de tobillo / pie",
    "synonyms": [
      "dolor talon",
      "dolor de talon",
      "dolor en talon",
      "molestia talon",
      "molestia en talon"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-tobillo-pie-tobillo",
    "system": "Musculoesqueletico",
    "medical": "dolor de tobillo / pie",
    "synonyms": [
      "dolor tobillo",
      "dolor de tobillo",
      "dolor en tobillo",
      "molestia tobillo",
      "molestia en tobillo"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dolor-tobillo-pie-tobillos",
    "system": "Musculoesqueletico",
    "medical": "dolor de tobillo / pie",
    "synonyms": [
      "dolor tobillos",
      "dolor de tobillos",
      "dolor en tobillos",
      "molestia tobillos",
      "molestia en tobillos"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dorsalgia-dorsal",
    "system": "Musculoesqueletico",
    "medical": "dorsalgia",
    "synonyms": [
      "dolor dorsal",
      "dolor de dorsal",
      "dolor en dorsal",
      "molestia dorsal",
      "molestia en dorsal"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "dorsalgia-espalda-alta",
    "system": "Musculoesqueletico",
    "medical": "dorsalgia",
    "synonyms": [
      "dolor espalda alta",
      "dolor de espalda alta",
      "dolor en espalda alta",
      "molestia espalda alta",
      "molestia en espalda alta"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "naproxeno",
      "diclofenaco",
      "paracetamol"
    ],
    "confidence": "medium"
  },
  {
    "id": "epilepsia",
    "system": "Neurologia",
    "medical": "epilepsia / crisis convulsiva",
    "synonyms": [
      "epilepsia",
      "convulsion",
      "crisis convulsiva",
      "ataque epileptico"
    ],
    "activeIngredients": [
      "levetiracetam",
      "valproato",
      "lamotrigina",
      "diazepam"
    ],
    "confidence": "low"
  },
  {
    "id": "epistaxis",
    "system": "ORL",
    "medical": "epistaxis",
    "synonyms": [
      "epistaxis",
      "sangrado nasal",
      "sangre nariz"
    ],
    "activeIngredients": [
      "acido tranexamico"
    ],
    "confidence": "low"
  },
  {
    "id": "epoc",
    "system": "Respiratorio",
    "medical": "EPOC",
    "synonyms": [
      "epoc",
      "enfermedad pulmonar obstructiva cronica",
      "bronquitis cronica"
    ],
    "activeIngredients": [
      "tiotropio",
      "salbutamol",
      "formoterol",
      "budesonida"
    ],
    "confidence": "low"
  },
  {
    "id": "faringoamigdalitis",
    "system": "ORL",
    "medical": "faringoamigdalitis",
    "synonyms": [
      "faringoamigdalitis",
      "amigdalitis",
      "anginas",
      "placas garganta"
    ],
    "activeIngredients": [
      "paracetamol",
      "ibuprofeno",
      "amoxicilina",
      "bencidamina"
    ],
    "confidence": "low"
  },
  {
    "id": "fibromialgia",
    "system": "Reumatologia / dolor",
    "medical": "fibromialgia",
    "synonyms": [
      "fibromialgia",
      "dolor generalizado",
      "dolor cronico generalizado"
    ],
    "activeIngredients": [
      "duloxetina",
      "pregabalina",
      "amitriptilina",
      "tramadol"
    ],
    "confidence": "low"
  },
  {
    "id": "glaucoma",
    "system": "Oftalmologia",
    "medical": "glaucoma",
    "synonyms": [
      "glaucoma",
      "tension ocular alta",
      "presion ocular alta"
    ],
    "activeIngredients": [
      "latanoprost",
      "timolol",
      "brimonidina",
      "dorzolamida"
    ],
    "confidence": "low"
  },
  {
    "id": "hipertiroidismo",
    "system": "Endocrinologia",
    "medical": "hipertiroidismo",
    "synonyms": [
      "hipertiroidismo",
      "tiroides alta",
      "tsh baja"
    ],
    "activeIngredients": [
      "tiamazol",
      "propiltiouracilo",
      "propranolol"
    ],
    "confidence": "low"
  },
  {
    "id": "hipotiroidismo",
    "system": "Endocrinologia",
    "medical": "hipotiroidismo",
    "synonyms": [
      "hipotiroidismo",
      "tiroides baja",
      "tsh alta"
    ],
    "activeIngredients": [
      "levotiroxina"
    ],
    "confidence": "low"
  },
  {
    "id": "impetigo",
    "system": "Dermatologia / infecciosas",
    "medical": "impetigo",
    "synonyms": [
      "impetigo",
      "costras mielicericas",
      "infeccion cutanea"
    ],
    "activeIngredients": [
      "mupirocina",
      "acido fusidico"
    ],
    "confidence": "low"
  },
  {
    "id": "incontinencia-urinaria",
    "system": "Urologia",
    "medical": "incontinencia urinaria",
    "synonyms": [
      "incontinencia",
      "incontinencia urinaria",
      "perdidas orina"
    ],
    "activeIngredients": [
      "solifenacina",
      "tolterodina",
      "mirabegron"
    ],
    "confidence": "low"
  },
  {
    "id": "infeccion-urinaria",
    "system": "Urologia / infecciosas",
    "medical": "infeccion urinaria",
    "synonyms": [
      "infeccion urinaria",
      "itu",
      "infeccion de orina",
      "urgencia miccional"
    ],
    "activeIngredients": [
      "fosfomicina",
      "nitrofurantoina",
      "amoxicilina"
    ],
    "confidence": "low"
  },
  {
    "id": "insuficiencia-cardiaca",
    "system": "Cardiovascular",
    "medical": "insuficiencia cardiaca",
    "synonyms": [
      "insuficiencia cardiaca",
      "edema piernas",
      "retencion liquidos",
      "fatiga cardiaca"
    ],
    "activeIngredients": [
      "furosemida",
      "bisoprolol",
      "enalapril",
      "espironolactona"
    ],
    "confidence": "low"
  },
  {
    "id": "menopausia",
    "system": "Ginecologia",
    "medical": "menopausia",
    "synonyms": [
      "menopausia",
      "sofocos",
      "sudores menopausia"
    ],
    "activeIngredients": [
      "estradiol",
      "progesterona",
      "tibolona"
    ],
    "confidence": "low"
  },
  {
    "id": "neumonia",
    "system": "Respiratorio / infecciosas",
    "medical": "neumonia",
    "synonyms": [
      "neumonia",
      "pulmonia",
      "infeccion pulmon"
    ],
    "activeIngredients": [
      "amoxicilina",
      "azitromicina",
      "levofloxacino",
      "paracetamol"
    ],
    "confidence": "low"
  },
  {
    "id": "neuropatia",
    "system": "Neurologia",
    "medical": "dolor neuropatico",
    "synonyms": [
      "dolor neuropatico",
      "neuropatia",
      "hormigueo",
      "parestesias"
    ],
    "activeIngredients": [
      "pregabalina",
      "gabapentina",
      "duloxetina",
      "amitriptilina"
    ],
    "confidence": "low"
  },
  {
    "id": "osteoporosis",
    "system": "Reumatologia / metabolismo oseo",
    "medical": "osteoporosis",
    "synonyms": [
      "osteoporosis",
      "huesos fragiles",
      "densidad osea baja"
    ],
    "activeIngredients": [
      "alendronato",
      "colecalciferol",
      "calcio",
      "denosumab"
    ],
    "confidence": "low"
  },
  {
    "id": "parkinson",
    "system": "Neurologia",
    "medical": "enfermedad de Parkinson",
    "synonyms": [
      "parkinson",
      "temblor reposo",
      "rigidez parkinson"
    ],
    "activeIngredients": [
      "levodopa",
      "carbidopa",
      "rasagilina",
      "pramipexol"
    ],
    "confidence": "low"
  },
  {
    "id": "prostatitis-hiperplasia",
    "system": "Urologia",
    "medical": "hiperplasia prostatica / prostatitis",
    "synonyms": [
      "prostata",
      "hiperplasia prostatica",
      "prostatitis",
      "dificultad orinar"
    ],
    "activeIngredients": [
      "tamsulosina",
      "dutasterida",
      "finasterida"
    ],
    "confidence": "low"
  },
  {
    "id": "psicosis",
    "system": "Salud mental",
    "medical": "psicosis",
    "synonyms": [
      "psicosis",
      "delirios",
      "alucinaciones",
      "brote psicotico"
    ],
    "activeIngredients": [
      "risperidona",
      "olanzapina",
      "quetiapina",
      "haloperidol"
    ],
    "confidence": "low"
  },
  {
    "id": "quemadura-solar",
    "system": "Dermatologia / curas",
    "medical": "quemadura solar",
    "synonyms": [
      "quemadura solar",
      "eritema solar",
      "piel quemada sol"
    ],
    "activeIngredients": [
      "dexpantenol",
      "hidrocortisona",
      "ibuprofeno"
    ],
    "confidence": "medium"
  },
  {
    "id": "reaccion-alergica",
    "system": "Alergia",
    "medical": "reaccion alergica",
    "synonyms": [
      "reaccion alergica",
      "alergia piel",
      "habones",
      "urticaria aguda"
    ],
    "activeIngredients": [
      "cetirizina",
      "loratadina",
      "dexclorfeniramina",
      "prednisona"
    ],
    "confidence": "medium"
  },
  {
    "id": "resaca",
    "system": "Sistemico / digestivo",
    "medical": "resaca",
    "synonyms": [
      "resaca",
      "cruda",
      "hangover",
      "malestar por alcohol",
      "dolor cabeza alcohol",
      "nauseas alcohol"
    ],
    "activeIngredients": [
      "ibuprofeno",
      "dimenhidrinato",
      "suero oral",
      "omeprazol"
    ],
    "confidence": "low"
  },
  {
    "id": "rinorrea",
    "system": "ORL",
    "medical": "rinorrea",
    "synonyms": [
      "rinorrea",
      "moqueo",
      "goteo nasal",
      "mocos liquidos"
    ],
    "activeIngredients": [
      "cetirizina",
      "loratadina",
      "ipratropio",
      "pseudoefedrina"
    ],
    "confidence": "medium"
  },
  {
    "id": "trombosis-anticoagulacion",
    "system": "Cardiovascular / hematologia",
    "medical": "trombosis / anticoagulacion",
    "synonyms": [
      "trombosis",
      "trombo",
      "anticoagulacion",
      "fibrilacion auricular"
    ],
    "activeIngredients": [
      "apixaban",
      "rivaroxaban",
      "acenocumarol",
      "warfarina"
    ],
    "confidence": "low"
  },
  {
    "id": "vulvovaginitis",
    "system": "Ginecologia / infecciosas",
    "medical": "vulvovaginitis",
    "synonyms": [
      "vulvovaginitis",
      "irritacion vaginal",
      "escozor vaginal",
      "picor vulvar"
    ],
    "activeIngredients": [
      "clotrimazol",
      "fluconazol",
      "metronidazol"
    ],
    "confidence": "low"
  }
];

export const GENERATED_RED_FLAG_RULES: RedFlagRule[] = [
  {
    "label": "anafilaxia",
    "terms": [
      "anafilaxia",
      "shock anafilactico",
      "reaccion alergica grave",
      "hinchazon labios lengua"
    ]
  },
  {
    "label": "deficit neurologico focal o convulsion",
    "terms": [
      "convulsion",
      "crisis convulsiva",
      "perdida fuerza",
      "dificultad hablar"
    ]
  },
  {
    "label": "dolor ocular o perdida visual",
    "terms": [
      "dolor ocular",
      "perdida vision",
      "vision borrosa brusca"
    ]
  },
  {
    "label": "fiebre con mal estado general",
    "terms": [
      "fiebre alta",
      "mal estado general",
      "decaimiento intenso"
    ]
  },
  {
    "label": "sangrado nasal persistente",
    "terms": [
      "epistaxis intensa",
      "sangrado nasal persistente"
    ]
  }
];
